modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="planeteer_core"
version="${file.jarVersion}"
displayName="Planeteer - Core"
credits="ZApp Dev team"
authors="ZApp Dev team"
description='''
This mod for the core of Planeteer.
'''

[[dependencies.planeteer_core]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.51,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.planeteer_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.planeteer_core]]
    modId="beyond_earth"
    mandatory=false
    versionRange="[6.2,)"
    ordering="AFTER"
    side="BOTH"